title: JASMIN Site
description: JASMIN web site implemented using Jekyll.
show_excerpts: true

plugins:
  - jekyll-feed

collections:
  staff_members:
    output: true
  about_items:
    output: true
  help_items:
    output: true
  users_items:
    output: true

collections_dir: collections

use_cacheBust: true

baseurl: "/jasmin-site-jekyll/"